### ISSUE TITLE
A problem becomes finalized/invalid when added to a list

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco-experiment#12]
We want to create a list of `bbob` problems because there are other (non-bbob) problems we would want to add to the list. However, when we add the `bbob` problems to the list, they become finalized/invalid.

The code

```python
import cocoex
suite = cocoex.Suite("bbob", "", "instance_indices: 1 function_indices: 1-2 dimensions:2")
problem_list = []
for problem in suite:
    print(problem)
    problem_list.append(problem)
print(problem_list)
```

returns

````
bbob_f001_i01_d02: a 2-dimensional single-objective problem (problem 0 of suite "b'bbob'" with name "BBOB suite problem f1 instance 1 in 2D")
bbob_f002_i01_d02: a 2-dimensional single-objective problem (problem 15 of suite "b'bbob'" with name "BBOB suite problem f2 instance 1 in 2D")
[<finalized/invalid problem>, <finalized/invalid problem>]
````

Is this behavior expected?

**Comment by ttusar** [comment]
Also, I do realize we now have the `BenchmarkFunction` interface for such usages (it would definitely cover our use case), but it is limited only to the "bbob" suite (we need this to work for "bbob-biobj-ext").

**Comment by nikohansen** [comment]
Yes, this is the expected behavior to avoid calling finalize explicitly in the usual benchmarking loop.

What you want is
```python
problem_list = [suite[i] for i in range(len(suite))]
```

**Comment by ttusar** [comment]
It works, thanks!
