### ISSUE TITLE
Data generated by calling `recommend` (.mdat files)

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco-experiment#7]
I ran an experiment on the `bbob-mixint` testbed while calling `recommend` after each iteration. This generated 2.5GB of data.

This is an example of the file sizes I see.
```
   8.1K Aug 30 12:49 bbobexp_f11_DIM80.dat
    42K Aug 30 13:18 bbobexp_f11_DIM80.tdat
   892B Aug 30 13:18 bbobexp_f11_DIM80.rdat
    11M Aug 30 13:18 bbobexp_f11_DIM80.mdat
```
This means, >99% of the data size comes from the recommendations. This doesn't look like coming close to a reasonable default behavior to me.

Many lines in the .mdat files do not improve the best (noise-free) fitness in my case, we see only 106 improvements in ~200,000 lines:

```python
d = np.loadtxt('bbobexp_f11_DIM80.mdat', comments='%')
f = d[:,2]
sum(diff(f) != 0), len(f)

  (106, 194568)

```
I don't think all these lines should be recorded by default (a reasonable exception would be the last call before the problem is finalized).

**Comment by nikohansen** [comment]
An example with 5 instances per function, removing `.mdat` files reduced the overall data size in my case by a factor of >10:
```sh
$ du -sh experiment026
  763M    experiment026
$ find experiment026 -name '*.mdat' -exec rm \{\} \; 
[...]
$ du -sh experiment026
  72M    experiment026
```

**Comment by ttusar** [comment]
We now decided that we won't make changes to how the bi-objective logger handles recommendations for the time being.

**Comment by nikohansen** [comment]
We may wanted to give a warning about file size when `recommend` is called for the first time.

**Comment by ttusar** [comment]
Done
